[build]
  command = "pip install -r requirements.txt"
  publish = "."

[functions]
  included_files = ["routes/**", ".env"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200